# This static class can filter the texts and remove most of the bad words
class_name Censorer


const Rules: Array[String] = [
	"n+([ehiy]+|ay|ey|io|[il]+)[bgq$]+h?(a+|aer|a+h+|a+r+|e+|ea|eoa|e+r+|ie|ier|let|lit|o|or|r+|u|uh|uhr|u+r+|ward|y+)s*",
	"f[ae]y?g+[oeiu]+t+s?",
	"даунская",
	"пидорасы",
	"ching\\W*chongs?",
	"n󠀡󠀡iggers",
	"re+t+a?r[dt]+s?",
	"towel\\W*heads?",
	"пидорка",
	"pac?k(i|ie|y)",
	"ting\\W*tongs?",
	"trann(ie|y)s?",
	"white\\W*trash",
	"ni:gg\\w*:\\w*",
	"chin(c|k)s?",
	"n+i+[gq]+s?",
	"yam\\W*yams?",
	"\\w*niggas?",
	"chinamans?",
	"polacke?s?",
	"neekeris?",
	"nigfhers?",
	"redskins?",
	"beaners?",
	"coolies?",
	"f+a+g+s*",
	"fenians?",
	"gringos?",
	"newfags?",
	"ni gg er",
	"nigga\\w*",
	"niggles?",
	"nignogs?",
	"rus+kis?",
	"wiggers?",
	"Ϝaggоt",
	"gypsies",
	"injuns?",
	"jiggas?",
	"nikkas?",
	"wiggas?",
	"\\w*fag",
	"coons?",
	"dykes?",
	"fa66ot",
	"fagts?",
	"gooks?",
	"gypos?",
	"homos?",
	"kikes?",
	"spics?",
	"abos?",
	"fgts?",
	"fаgs",
	"gypsy",
	"japs?",
	"wops?",
	"fagz",
	"fаg",
	"f@g",
	"\\w*N󠀡󠀡IGGE󠀡󠀡R\\w*",
	"\\w*ɴɪɢɢᴇʀ\\w*",
	"\\w*nіggеr\\w*",
	"\\w*NÍGGER\\w*",
	"\\w*n\\\\\\|gger\\w*",
	"\\w*niggеr\\w*",
	"\\w*F4GG0T\\w*",
	"\\w*N1GG3R\\w*",
	"\\w*nigger\\w*",
	"\\w*nigg4\\w*",
	"\\w*niggz\\w*",
	

	"fak(ed|ers?|ing)",
	"kompetenzteam",
	"æ´¾é€å‘˜",
	"pinegrove",
	"n\\.e\\.ig\\.e\\.",
	"fukushima",
	"nie gee",
	"fuchsia",
	"fuchian",
	"cock\\.li",
	"fuxius",
	"fucuro",
	"niego",
	"niebo",
	"neige",
	"neggy",
	"nebby",
	"fuxis",
	"cwfag",
	"pubg",
	"niby",
	"nebo",
	"fuku",
	"fuki",
	"fakt",
	
	"(ape|bat|bull?|butt|dip|dog|dumb|ebo|holy|horse|jack|pedo|pig|ubi)\\W*sh(it|ti)s?",
	"d[il]+(ck|kc)\\W*(ass|bag|breath|eat|face|flip|head|hole|less|suck|weed)\\w*",
	"f[chj]?(a|au|aw|e|o+|u|uy)[ch]*k(e?d|e?rs?|[ei]?n+g?|t)",
	"m[aou](d+|t+|th|ht|z)(a|e|er|ir|ur)(c|f)c?[aou]c?k\\w*",
	"m[ou]th(a|er)(f|ph)[vue]+c?[gkqx]+(e?d|e?r|[ei]?n+g?)",
	"\\w*f[vu]+h*c+[hjvk]*(e?d|e?r|[ei]?n+g?|t)",
	"b+i+a*t+c+h+(e+d|e*r?[sz]+|[ei]?n+g?|y)",
	"\\w*f[vu]+c?[xkq]+(e?d|e?r|[ei]?n+g?|t)",
	"p(oo+|u+)s+(a+y+|e+|eh|ey|i+|ie|y+)s*",
	"m[ou]th(a|er)(f|ph)[vue]+c?[gkqx]+",
	"\\w*f[vu]+h*q(e?d|e?r|[ei]?n+g?|t)",
	"f[chj]?(a|au|aw|e|o+|u|uy)[ch]*k",
	"f[ck]+(e?d|e?r|[ei]?n+g?|t)",
	"fu󠀡󠀡cki󠀡󠀡ng",
	"dumb(f|ph)[vu]+c?[xkq]",
	"c(oc?|aw)k\\W*suc?k\\w*",
	"d[il]+(ck|kc)(ed|ing)",
	"ph[vu]+h*c+[hjvk]*\\w*",
	"son\\W*of\\W*a\\W*bitch",
	"долбоебизм",
	"c(o|ah|aw)c?k(s|ed)",
	"s+h+[ily]+t+[ersy]*",
	"a+ss+\\W*w?hole?\\w*",
	"ph[vu]+c?[xkq]+\\w*",
	"говноедов",
	"долбаебов",
	"ебланская",
	"ебланский",
	"заебёшься",
	"захуячили",
	"съебаться",
	"пидарский",
	"уебанский",
	"уебищьное",
	"f[vu]+c?[xkq]+\\w*",
	"bull+sh+[ily]+t+",
	"god\\W*damn?\\W*it",
	"ахуенная",
	"ахуенную",
	"ахуенный",
	"выебаное",
	"ебанному",
	"ебанутые",
	"ебланами",
	"пидарасы",
	"уёбищная",
	"уёбищный",
	"god\\W*damn?\\w*",
	"въебали",
	"въебать",
	"ебанная",
	"ебанное",
	"ебанных",
	"ебаного",
	"ебаньки",
	"ебонное",
	"заебала",
	"заебало",
	"поебень",
	"хуёвого",
	"a+ss+\\W*fu\\w*",
	"c(o|ah|aw)c?k",
	"d[il]+(ck|kc)",
	"b+i+a*t+c+h+",
	"butt\\W*fu\\w*",
	"cumm(er|ing)",
	"f[vu]+h*c\\w*",
	"f[vu]+h*q\\w*",
	"sh+i+[ae]+t+",
	"ахуели",
	"ебаная",
	"ебаное",
	"ебаной",
	"ебаную",
	"ебаные",
	"ебаный",
	"ебаным",
	"ебаных",
	"ебучий",
	"пиздеж",
	"пиздец",
	"сраная",
	"уёбища",
	"уёбище",
	"хуесос",
	"хуетой",
	"хуйнёй",
	"хуёвая",
	"хуёвый",
	"c+u+n+t+\\w*",
	"d+i+c+k+s*",
	"fucking",
	"блядь",
	"блять",
	"дохуя",
	"дрочи",
	"ебало",
	"ебать",
	"н4еб4л",
	"нахуй",
	"нахуя",
	"нехуй",
	"нихуя",
	"пизде",
	"пизду",
	"похуй",
	"уебёт",
	"хуета",
	"хуету",
	"хуйни",
	"хуйню",
	"хуйня",
	"ёбаны",
	"a+sholes?",
	"sh+e+i+t+",
	"ахуе",
	"ебал",
	"ебут",
	"сука",
	"хуям",
	"шлюх",
	"F\\.U\\.C\\.K",
	"chodes?",
	"cumshot",
	"fucking",
	"fuck",
	"shit\\w*",
	"shtpost",
	"who+re?",
	"cumbag",
	"jebane",
	"sluts?",
	"slutty",
	"twats?",
	"бля",
	"ебу",
	"хуи",
	"хуй",
	"хуя",
	"cums?",
	"dafuq",
	"diсk",
	"sh it",
	"coq+",
	"hore",
	"kock",
	"shat",
	"dik",
	"fck",
	"\\w*f+u+c+k+\\w*",
	"\\w*fцск\\w*",
	"\\w*shіtty\\w*",
	"\\w*f_uc_k\\w*",
	"^[a@][s\\$][s\\$]$",
	"[a@][s\\$][s\\$]h[o0][l1][e3][s\\$]?",
	]


static func filter_list(texts: Array[String] = [], censor_character: String = "*") -> Array[String]:
	var censored_texts: Array[String] = []
	
	for text in texts:
		censored_texts.append(filter(text))
		
	return censored_texts
	

static func filter(text: String, censor_character: String = "*") -> String:
	var new_text: String = text
	var regex = RegEx.new()
	
	for rule in Rules:
		regex.compile(rule)
		
		var result: RegExMatch = regex.search(new_text)
		
		if is_instance_valid(result):
			for profanity in result.strings:
				var censored_string: String = ""
				
				for _i in profanity.length():
					censored_string += censor_character
				
				new_text = new_text.replace(profanity, censored_string)
		
	return new_text
